# Project Structure:
# .github/workflows/collect_aqi.yml
name: Collect AQI Data

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dotenv logging
          
      - name: Run collection script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python collect_aqi.py
        
      - name: Set up GitHub token
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git config --global credential.helper store
          echo "https://${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
          
      - name: Commit and push if changed
        run: |
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update AQI data [skip ci]" && git push)
